### ISSUE TITLE
Multiple machines fails with error

### ISSUE THREAD

**Issue by myaesubi** [mdaslamansari/ApplicationPoolStartStop#1]
Hi @mdaslamansari ,
Thanks for the task it helped me quite a bit. 

I came across using multiple machines addresses; IPs which are comma separated to stop or start same app pool on multiple servers. But It appears the PowerShell script supporting the tasks does not like it and throws error.

I wonder if I miss something.

Thank you,
Mohammad
#

**Comment by mdaslamansari** [comment]
Issue resolved.

**Comment by Hgker01** [comment]
Hi @mdaslamansari!

I have just installed this task yesterday, and I would like to use it for manage app. pools on multiple servers. I used comma separeted FDQNs. Unfortunately I have got this error: "##[error]System.ArgumentException: One or more computer names are not valid. If you are trying to pass a URI, use the -ConnectionUri parameter, or pass URI objects instead of strings."
With one FDQN it works fine.

Colud you resolve this issue again?

Many thanks,
Gábor
